### ISSUE TITLE
Undefined property: stdClass::$email

### ISSUE THREAD

**Issue by lanoow** [JakyeRU/Larascord#1]
Hello Jakye,
I tried using Larascord, but I got the error in the title. Did everything. Went all default on the installation options.
Screenshot: [click here](https://prnt.sc/20s7s2d)

**Comment by JakyeRU** [comment]
Hello @lanoow. I have released [v1.0.1](https://github.com/JakyeRU/Larascord/releases/tag/v1.0.1) with a hotfix. Do you still experience the error?

**Comment by lanoow** [comment]
Will try it later
