### ISSUE TITLE
[BUG] Getting Users Mail Address 

### ISSUE THREAD

**Issue by TFWIsaac** [JakyeRU/Larascord#100]
**Describe the bug**
In my .env i have the following scope:
`LARASCORD_SCOPE=identify&guilds&guilds.members.read`
I do not want the mail addresses of my users, but i get them how ever...

The Scope documentary: https://discord.com/developers/docs/topics/oauth2

identify | allows /users/@me without email

I do not have a clue, where this comes from. Even in the discord promt for the auth is nothing with the mail address wich will be shared.

Please ensure some Method or config option, to remove this behaviour.

At this situation i must setup a database trigger. This trigger sets after update the email colum to NULL

**Comment by JakyeRU** [comment]
If the user authorized your application with the `email` scope in the past, even though there is no e-mail scope in the present, Discord's API will still return an e-mail.

**Comment by JakyeRU** [comment]
Do you still need help with this issue?

**Comment by TFWIsaac** [comment]
No thank you, for new users there are entries.
