### ISSUE TITLE
[FEATURE] Discord guild specific username

### ISSUE THREAD

**Issue by TFWIsaac** [JakyeRU/Larascord#101]
For every discord guild you can set a specific username. By default you have not set such a username, but it is possible to set this.

So i request to implement a new colum in the user table with this username. You can do it like the roles colum. A JSON object with each guild and the username. If its not set, then there should be NULL.

My Example:

`{
   "123456789": "Guild-specific-username",
   "987654321" NULL
}`

**Comment by JakyeRU** [comment]
Hello @TFWIsaac,

I'll probably add a "guilds" column that includes the GuildMember objects for the servers if the access token has the necessary scope for that.

**Comment by TFWIsaac** [comment]
Are there any new news about that? Its a really cool and necessary feature for me.

**Comment by JakyeRU** [comment]
Hello,

I've been a bit busy for the last couple of weeks. I'll try to add it ASAP. Thank you for your patience. :)

**Comment by JakyeRU** [comment]
This was added in [v5.0.5](https://github.com/JakyeRU/Larascord/releases/tag/v5.0.5).

https://larascord.jakye.me/interacts_with_discord#getguildmember
