### ISSUE TITLE
[FEATURE] make it so it only does what it is supposed to and not deletes everything you have done

### ISSUE THREAD

**Issue by SorryX** [JakyeRU/Larascord#102]
I am a bit mad because this library literally removed everything I have been working on for the past 4 days, I was able to recover some of it but this library still messed up a lot,

Make it so it doesn't delete everything and installs a whole new laravel project, it should be just something you add and use the feature you want to and change the whole project configuration, just do so people can configure what they want and not so they don't end up like me and lose all progress thinking they only downloading a simple library like laravel socialite

**Comment by JakyeRU** [comment]
Hello @SorryX,

I am sorry to hear that. Larascord installs Laravel Breeze in the project and updates it with the necessary file modifications to make everything work.

It is not recommended to install Larascord in an already-existing project, as per the [warning in the documentation](https://larascord.jakye.me/getting_started/laravel).

To prevent this from happening again I suggest you use a version control system, such as Git.

Currently, there are no plans of changing Larascord's install behavior.
