### ISSUE TITLE
[BUG] User will be created in database despite it the user has not the certain roles

### ISSUE THREAD

**Issue by TFWIsaac** [JakyeRU/Larascord#107]
I have found the following bug:

If you have enabled that a user must be member of a certain guild with certain roles then this bug occurs:

If the user is member of the guild and has not the certain roles as defined, the user will despite it created in the user table and that is strange.

Please fix this behaviour, its really strange for me, that users occurs in my user table without the certain roles.

**Comment by JakyeRU** [comment]
The issue should now be fixed in [v5.0.6](https://github.com/JakyeRU/Larascord/releases/tag/v5.0.6). Thank you for reporting it!

**Comment by TFWIsaac** [comment]
i am sure, this broke something... After updating to new version i got this error:

Jakyeru\Larascord\Services\DiscordService::hasRoleInGuild(): Argument #1 ($user) must be of type App\Models\User, Jakyeru\Larascord\Types\User given

**Comment by TFWIsaac** [comment]
I think this come from: https://larascord.jakye.me/interacts_with_discord#getguildmember

This is the complete message:

Jakyeru\Larascord\Services\DiscordService::hasRoleInGuild(): Argument #1 ($user) must be of type App\Models\User, Jakyeru\Larascord\Types\User given, called in C:\laragon\www\ttt-ng\vendor\jakyeru\larascord\src\Http\Controllers\DiscordController.php on line 87

**Comment by JakyeRU** [comment]
I deleted the release. I'll take a look at it as soon as possible.

**Comment by JakyeRU** [comment]
The new patch should work this time. I've used database transactions to make sure everything goes smoothly during the login process.
