### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by DamoFD** [JakyeRU/Larascord#112]
**Is your feature request related to a problem? Please describe.**
Fetching guild member counts is a separate URL.

**Describe the solution you'd like**
Thinking maybe a separate method, or adding member counts to the current fetch guilds method in DiscordService.

**Additional context**
I added member counts to the current fetch guilds method to fit my personal needs in my project, I would like to contribute this method, or create a second method that includes the guild member counts to fit other's needs that may want this feature.

**Comment by JakyeRU** [comment]
Hello @DamoFD,

That sounds great! You're welcome to submit a PR adding this feature. Don't forget to add the method to the `InteractsWithDiscord` trait and to the documentation.

Thank you. :)

**Comment by DamoFD** [comment]
Perfect, I'll PR in a day or two 👍
