### ISSUE TITLE
[FEATURE] Rename 'roles' database column to 'discord_roles'

### ISSUE THREAD

**Issue by Lamineslot** [JakyeRU/Larascord#120]
**Is your feature request related to a problem? Please describe.**
I'm currently using Larascord, while also attempting to use the [Laravel permission package by Spatie](https://github.com/spatie/laravel-permission). I've recently run into errors using the permissions package. While debugging the issue, I found the issue.
![image](https://github.com/JakyeRU/Larascord/assets/71119665/153fe1cc-841c-4ec9-8fc9-d79b705c5a0a)

The user model may not have a 'roles' attribute for the Permissions package to work. Larascord adds a 'roles' attribute, thus causing this issue.

**Describe the solution you'd like**
It'd be awesome if you could change the 'roles' column to 'discord_roles'. This does not have a negative effect on the other users of the package, while allowing users to use the very popular Laravel permission package by Spatie.

**Comment by JakyeRU** [comment]
Hello @Lamineslot,

Thanks for the heads up. 

The column will be renamed to `discord_roles` or I will create another table and create a relationship between it and the user.

**Comment by Lamineslot** [comment]
Awesome, thanks!

**Comment by JakyeRU** [comment]
I have decided to remove the `roles` column entirely.

In case you need to get a user's roles in a guild you can use [getGuildMember](https://larascord.jakye.me/interacts_with_discord#getguildmember) and store it in your own way.
