### ISSUE TITLE
[FEATURE] Templates

### ISSUE THREAD

**Issue by DamoFD** [JakyeRU/Larascord#121]
**Is your feature request related to a problem? Please describe.**
Fetch templates

**Describe the solution you'd like**
Template type, and fetch template method

**Additional context**
Not sure what path you're looking for Larascord to take, but in the application we're developing we have added template, and bot advertising. Templates do not require OAuth, so not sure if you'd like this feature added.

However if you're looking to expand Larascord to handle more aspects of Discord aside from OAuth, I'd be happy to implement server template fetching. And later on bot fetching.

**Comment by JakyeRU** [comment]
Hello @DamoFD,

For the last couple of months, I have been debating what path should Larascord take and I'm still not really sure. Larascord has been originally designed to handle Discord's OAuth2 login flow. I was thinking of creating another package as a wrapper around Discord's API and leaving Larascord as it is.

I'm not sure what will happen yet.

**Comment by DamoFD** [comment]
@JakyeRU for sure, well, when you decide the best path of action let me know, I'd love to work on it 👍

**Comment by JustGregGithub** [comment]
Adding onto this. I think larascord would be perfect as a all-in-one provider for discord in laravel.

If someone is going to use discords api, It would make sense for them to use the discord oauth for their users.

**Comment by JakyeRU** [comment]
Hello @JustGregGithub,

I appreciate your input and insights regarding the integration of Larascord as an all-in-one provider for Discord within the Laravel framework.

However, I would like to point out a crucial consideration. If we decide to pursue this path, a substantial revision of Larascord will be necessary to align its functionality more closely with Laravel Socialite.

Right now, Larascord needs to be installed in a new project as it also installs Laravel Breeze and may override changes you've made to your project.

**Comment by JakyeRU** [comment]
I've decided it's a good idea to revamp Larascord and make it behave more like Laravel Socialite. This way, you won't have to create a whole new Laravel project just to use Larascord. (#102)

I added a notice in the readme and I will be closing this issue and #124.
