### ISSUE TITLE
[BUG] Roles column not filled

### ISSUE THREAD

**Issue by jnijland** [JakyeRU/Larascord#122]
**Describe the bug**
On a clean installation following the installation guide on the documentation, the roles column stays empty. I would like to know which roles a user has on the Discord server.

**To Reproduce**
1. Create a clean installation of Larascord following the official documentation; 
2. Log in to your new Laravel application;
3. The roles column is empty.

**Expected behavior**
I would like the roles column to be filled with the users roles (or role ids).

**Screenshots/Videos**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Google Chrome 116.0.5845.111 (Officiële build) (64-bits)
 - Laravel 10.21.0
 - PHP 8.1.22

**Additional context**

**Comment by jnijland** [comment]
I did try adding the guilds and guilds.members.read scopes, but that didn't solve it either.

**Comment by JakyeRU** [comment]
Hello @jnijland,

The roles column will only be updated if you restrict access to the application to specific roles. (See `guild_roles` in the configuration)

**Comment by jnijland** [comment]
Hi @JakyeRU, 

If I understand correctly, this means it is not possible to get a users Discord role(s)?

Thank you

**Comment by JakyeRU** [comment]
You can by using this method: https://larascord.jakye.me/interacts_with_discord#getguildmember
