### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by evarioooo** [JakyeRU/Larascord#134]
Hello, is it possible to use MongoDB instead of MySQL? What changes would I need to make?

Have a nice day

**Comment by JakyeRU** [comment]
Hello @evarioooo,

Theoretically yes, it is possible, but some changes need to be made. MongoDB has [an article](https://www.mongodb.com/developer/languages/php/laravel-mongodb-tutorial/) about it.

Larascord won't support nor try to add support for MongoDB as it is beyond the package's scope.
