### ISSUE TITLE
[BUG] No scopes where provided

### ISSUE THREAD

**Issue by SrPeterr** [JakyeRU/Larascord#22]
**Describe the bug**

**To Reproduce**
1. Install Laravel: `curl -s https://laravel.build/main-app| bash` then `cd main-app`
2. Edit .env for the mysql data
3. Install Larascord `composer require jakyeru/larascord` & `php artisan larascord:install`
4. CLIENT ID and CLIENT SECRET:
![image](https://user-images.githubusercontent.com/21348463/149182284-d7a89d42-6dab-49be-a1ae-fd137f14087b.png)
![image](https://user-images.githubusercontent.com/21348463/149182699-17bc3e49-5af3-4c15-b06c-dfdd0acd6a3e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser + Version: Brave
 - Laravel Version: v8.79.0
 - PHP Version: v8.0.14

**Additional context**
I did change at the end
`APP_URL=https://exi.srpeter.com/`
![image](https://user-images.githubusercontent.com/21348463/149183567-a1a22d55-c6b8-4c8f-a41e-b8f6d7a747da.png)

**Comment by JakyeRU** [comment]
Hello, thanks for reporting this bug.

Seems like the required variables are not loaded from `.env`. Can you confirm that the following variables exist in `.env`?
- LARASCORD_CLIENT_ID
- LARASCORD_CLIENT_SECRET
- LARASCORD_GRANT_TYPE
- LARASCORD_PREFIX
- LARASCORD_SCOPE


If they do, it might be work trying clearing the cache:
```shell
php artisan config:clear
```

**Comment by SrPeterr** [comment]
Hello!

Yes, they do exist and there are the correct ones
And I did clear the cache, still the same :(

**Comment by JakyeRU** [comment]
Hello.

Please open a terminal in your project's directory and open up Tinker using:
```shell
php artisan tinker
```
Once Tinker has been opened, check if the environment variables and Larascord's configuration return correct values:
```shell
env('LARASCORD_CLIENT_ID')
```
```shell
config('larascord.client_id')
```

Example:
![image](https://user-images.githubusercontent.com/36800842/149189015-409b0ecf-bd9e-493a-8ed1-b368e106a379.png)

**Comment by SrPeterr** [comment]
Hi!

So `env('LARASCORD_CLIENT_ID')` give me the correct client id
But `config('larascord.client_id')` returns null

**Comment by JakyeRU** [comment]
> Edit: For some reason, I did check the github and I think the necessary fieles weren't created, I can't see the config/config.php

The `config/config.php` from Larascord's source code will be copied to `config/larascord.php` in your application.
https://github.com/JakyeRU/Larascord/blob/3671668fdf82b898dc66cc2afc612605f1287205/src/LarascordServiceProvider.php#L37

Does it exist in your application?

**Comment by SrPeterr** [comment]
> Does it exist in your application?

Nope `config/larascord.php` is not there

**Comment by JakyeRU** [comment]
> > Does it exist in your application?
> 
> Nope `config/larascord.php` is not there

Please try running one of these commands:
```shell
php artisan larascord:publish --force
```
```shell
php artisan vendor:publish --provider="Jakyeru\Larascord\LarascordServiceProvider" --tag="config"
```

**Comment by SrPeterr** [comment]
I did try the first one, and same problem, tried the second on and got this error

![image](https://user-images.githubusercontent.com/21348463/149191526-19e5ce13-9359-4cdf-8578-622992ff8dcb.png)

Just in case, I went to the route:
![image](https://user-images.githubusercontent.com/21348463/149191737-362db210-cb98-4a1b-8b21-61282f188b0b.png)

**Comment by SrPeterr** [comment]
Ok, perfect, and no problem, thanks for your time! :)

**Comment by JakyeRU** [comment]
Please re-install Larascord in a new project (just to make sure) and confirm that the issue is gone.
