### ISSUE TITLE
[FEATURE] More Config Options

### ISSUE THREAD

**Issue by TFWIsaac** [JakyeRU/Larascord#24]
**Is your feature request related to a problem? Please describe.**
Hey my FR is not related to a problem.

I have three things:

1. Possibility to publish your things from vencdor to the "app" area to edit them. (Maybe its already possible and i am stupid to read the docs).
2. Option to set the "prompt" setting to the .env. Im my case i want to see this message from Discord.
3. Some Entrypoint to enter own Code after the successfull and unsuccessfull login. In my case, i want to check if the user is on a specific guild.

For more Information just ask.

Thanks for your work JakyeRU!

**Comment by JakyeRU** [comment]
Hello,

Thank you for your suggestions. 

1. You can already publish your configuration using:
```shell
php artisan larascord:publish
```
You shouldn't need this command though, as the configuration is automatically published when you install the package. You should find the configuration file in `config/larascord.php`.

2. I have added the option to set the prompt in `config/larascord.php` in https://github.com/JakyeRU/Larascord/commit/4645f2d9810b38872072a1e4971b0391ee7fe5cf.

3. This is a great suggestion that will get implemented in the near future.

Thank you!

**Comment by JakyeRU** [comment]
> 3\. Some Entrypoint to enter own Code after the successfull and unsuccessfull login. In my case, i want to check if the user is on a specific guild.

@TFWIsaac I've created a pull request (#33) that will add 2 events. You can create a listener to listen to these events.
