### ISSUE TITLE
[BUG] Something went wrong! The authorization code is invalid.

### ISSUE THREAD

**Issue by JustLuucy** [JakyeRU/Larascord#27]
**Describe the bug**
I installed the plugin as shown and also followed the necessary configuration steps, but after logging into discord I get the message "Something went wrong! The authorization code is invalid." and I'm not logged in. I don't know what i did wrong.

**To Reproduce**
- createt fresh laravel project with composer
- installed php 8.1.1 and made shure, that laravel is using this version
- followed the installation instructions as listed

**Expected behavior**
The authorization process should proceed without errors.

**Screenshots/Videos**
 ![Screenshot_1423](https://user-images.githubusercontent.com/38688739/150048182-c22d7b23-6fd1-4111-8788-4da8aa1fa2ff.png)

**Desktop (please complete the following information):**
 - Windows 11 Version 21H2 (Build 22000.434)
 - Google Chrome Version 97.0.4692.71 (Offizieller Build) (64-Bit)
 - Laravel Framework 8.80.0
 - PHP 8.1.1 (cli) (built: Dec 15 2021 10:31:43) (ZTS Visual C++ 2019 x64)

**Additional context**
I have no idea if or what I did wrong. I followed the instructions, but I didn't get any further error messages as shown in the screenshot. I would like to use this plugin because it makes things a lot easier and I absolutely need a web-based dashboard for my discord bot.

**Comment by JakyeRU** [comment]
Hello @JustLuucy,
Can you make sure that `LARASCORD_CLIENT_ID` and `LARASCORD_CLIENT_SECRET` are set correctly in `.env`.?

**Comment by JustLuucy** [comment]
Sorry for my late response. Yes i did everything correct. I used the automated Install command.

**Comment by JakyeRU** [comment]
Hello,

Please update Larascord to the latest version ([v3.0.5](https://github.com/JakyeRU/Larascord/releases/tag/v3.0.5)) and set `APP_DEBUG` to `true` in `.env`.

This should show you exactly why you get that error.

**Comment by JustLuucy** [comment]
```json
{
"larascord_message": "The authorization code is invalid.",
"message": "cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://discord.com/api/oauth2/token",
"code": 0
}
```

**Comment by JakyeRU** [comment]
Hello,

Thanks for the update. This issue is not caused by Larascord and is relatively simple to fix.

Step 1: Download [cacert.pem](https://curl.se/ca/cacert.pem)
Step 2: Move it to `C:\php\extras\ssl`. *this location may differ on your system*
Step 3: Edit `C:\php\php.ini` and add the certificate information:
```ini
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
curl.cainfo = "C:\php\extras\ssl\cacert.pem"
```

Everything should be working now.

**Comment by JustLuucy** [comment]
it is working how it should. thank you very much

**Comment by JakyeRU** [comment]
You're welcome.

**Comment by himamshah** [comment]
not working with this solution also,

**Comment by JakyeRU** [comment]
@himamshah Is your server using the correct PHP version, the one you modified?

**Comment by MoAudi** [comment]
How did you solve it?? I have the same error.

**Comment by JakyeRU** [comment]
> How did you solve it?? I have the same error.

Check this answer: https://github.com/JakyeRU/Larascord/issues/27#issuecomment-1018638356
