### ISSUE TITLE
"HTTP request returned status code 429"

### ISSUE THREAD

**Issue by 69u** [JakyeRU/Larascord#32]
Hello there,

I have been using Larascord for a few days now and have changed up the guild_only function to suit my needs. Basically i am using the pre-made function getUserGuilds to store the users guilds along with their data each time they authenticate.

The only problem is that the server is hitting Discord's rate limit after very few attempts which is obviously a huge issue.

Just wanted to check if there were any quick solutions to this problem!

**Comment by JakyeRU** [comment]
Hello @69u,

Discord's rate limit is currently 10,000 requests per 10 minutes (around 16 to 17 requests per second). I tried logging in and logging out several times (with `guild_only` set to `true` in `larascord.php`) and I can't reach the API limit. 

Is your server making requests to Discord from other applications?

**Comment by 69u** [comment]
> Hello @69u,
> 
> 
> 
> Discord's rate limit is currently 10,000 requests per 10 minutes (around 16 to 17 requests per second). I tried logging in and logging out several times (with `guild_only` set to `true` in `larascord.php`) and I can't reach the API limit. 
> 
> 
> 
> Is your server making requests to Discord from other applications?

The Discord Bot is also running on the same server which now that you mention it makes a lot more sense.

I will try allocating another IP to my azure vm and let you know how I go 😀

**Comment by 69u** [comment]
Hey again,

After a few days of testing I have discovered the issue is not with the Discord API rather with Laravel communicating with the database.

I am in the max guilds you can be in on Discord so I assume I'm hitting some form of MySQL limitation.

I have also tried json_encode and had no luck.

I have edited the following lines in my User Model:

protected $fillabe = [
      //
      'guilds'
      //
];

protected $casts = [
       //
      'guilds' => 'json',
      //
  ];

and I have added the following to my Discord Controller

return User::updateOrCreate(
            [
                'id' => $user->id,
            ],
            [
                //
                'guilds' => $userGuilds ?? NULL,
               //
           ])

Any help would be appreciated heavily!

**Comment by JakyeRU** [comment]
Have you modified the users migration file?

**Comment by 69u** [comment]
I have finally resolved the issue, which indeed was in the migration file. All I had to do was reset the migration and migrate it again and everything seems to be working 👍 

It was set as a String in the Migration but a longText in the database so Laravel obviously thought I was hitting MySQLs max limit!

Cheers for your help mate, appreciate it dearly 😄

**Comment by JakyeRU** [comment]
I'm glad you were able to fix it. :)
