### ISSUE TITLE
[BUG] Re-Login via Discord

### ISSUE THREAD

**Issue by 536f6e6179** [JakyeRU/Larascord#38]
Registering and saving to the database works without problems but as soon as you log out to log in again, you get 
`{"larascord_message":"There was an error with the database. Please try again later.","message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry `

because he is trying to create the same user instead of login again with discord.

**Comment by JakyeRU** [comment]
Hello @536f6e6179,

Please follow the [bug report format](https://github.com/JakyeRU/Larascord/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D). Giving as much information as possible is helpful in tracking down the bug and fixing it.

Thank you!
