### ISSUE TITLE
[FEATURE] Multiple (sub)domain support

### ISSUE THREAD

**Issue by jnijland** [JakyeRU/Larascord#40]
**Is your feature request related to a problem? Please describe.**
I'm not able to use Larascord for authentication over multiple subdomains (on the same Laravel installation), I'm ending in a endless redirect loop. Authentication worked before I changed the routing setup to allow a main domain and subdomain. 

**Describe the solution you'd like**
I would like to be able to share my Discord login over multiple subdomains and the main domain off my application. 

**Describe alternatives you've considered**
I've used a few StackOverflow pages since I've had some difficulties with sharing authentication over multiple subdomains in the same laravel installation. For example: 
https://stackoverflow.com/a/56500425

**Additional context**

**Comment by JakyeRU** [comment]
Hello @jnijland,

This should work by default as Larascord uses `Illuminate\Support\Facades\Auth` to authenticate users.
Please add the following to your `.env`, clear the cookies, and try to login again:
```env
SESSION_DOMAIN=".yourdomain.com"
```

The only error you may get is 
```json
{"larascord_message":"The authorization code is invalid.","message":"HTTP request returned status code 400:\n{\"error\": \"invalid_grant\", \"error_description\": \"Invalid \\\"redirect_uri\\\" in request.\"}\n","code":400}
```

If that does happen please let me know.

**Comment by jnijland** [comment]
Hi @JakyeRU, 

I already tried this the day before and it didn't work. Somehow, after a good night sleep, it works now (left my PC on overnight and didn't do anything with my cookies). Sorry for bothering and thanks for the suggestion!

**Comment by JakyeRU** [comment]
Hello @jnijland ,

I'm glad the issue has been resolved. If it does happen again don't hesitate to open another issue. 😄
