### ISSUE TITLE
[BUG] The Authorization Code is Invalid

### ISSUE THREAD

**Issue by ZachHandley** [JakyeRU/Larascord#42]
**Describe the bug**
After install, I ran `php artisan larascord:install` and it installed correctly, I ran the migration, and now when I hit my `/login` route it works, then it says, "The authorization code is invalid." 401 code

**To Reproduce**
1. Go to https://growsolar.us/main
2. Click on Login
3. Authenticate

**Expected behavior**
Login

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 11
 - Browser + Version [e.g. Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)] -- Firefox latest
 - Laravel Version [e.g. v8.6.10] -- 9.XX
 - PHP Version [e.g 8.1.1] 8.1.X

**Additional context**

**Comment by JakyeRU** [comment]
Hello @ZachHandley,

Please make sure that `LARASCORD_CLIENT_SECRET` in `.env` is correct. An invalid secret will cause this error.

**Comment by ZachHandley** [comment]
Ah I understand, thank you for that!
