### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by SnyderWillCode** [JakyeRU/Larascord#56]
Will this support Laravel Jetstream?

**Comment by JakyeRU** [comment]
Larascord uses Laravel Breeze for the UI. There are no plans of changing it with Laravel Jetstream as Discord handles user verification and 2-factor authentication.

**Comment by SnyderWillCode** [comment]
Is it possible if I can take larascord and implement it to Jetstream since I want to keep 2 factor auth and verification for  normal email and pass, since I want to have 2 authentication systems. and let users connect their discord accounts to it.

**Comment by JakyeRU** [comment]
Yes, since Larascord is licensed under [MIT](https://github.com/JakyeRU/Larascord/blob/main/LICENSE) you can create a fork of the repository and make any edits you want to the package.

**Comment by SnyderWillCode** [comment]
Ok, thank you, hopefully I manage to get it done.
