### ISSUE TITLE
[FEATURE] After login redirect

### ISSUE THREAD

**Issue by TFWIsaac** [JakyeRU/Larascord#98]
Hey i have just installed a fresh version of Larascord. 

After a login, i will get a redirect to `/home`, but i dont need this and i dont find any config option to change these.

In my `routes/web.php ` i have the following work-a-round;

```
Route::get('/home', function () {
    return redirect('/');
});
```

So it would very nice to have these option to set a route.

**Comment by JakyeRU** [comment]
Larascord redirects to the home page defined in App\Providers\RouteServiceProvider::HOME. Changing that setting should fix your issue.
