### ISSUE TITLE
[BUG] Not found Bug with multiple guilds

### ISSUE THREAD

**Issue by TFWIsaac** [JakyeRU/Larascord#99]
**Describe the bug**
I have found out that in the DiscordController.php a simple but fatal error is with multipe guilds. This only occurs when a discord user is member only server (of 2 in this case)

In the Controller we have on [line 88](https://github.com/JakyeRU/Larascord/blob/2a869aceb972fd25aa56556f7ac8f7d75fa4dbbd/src/Http/Controllers/DiscordController.php#L88) a foreach loop, wich cause the problem.

But step by step.

In my case i have set in the `config/larascord.php` by the key `"guilds"` two Discord-Servers, like the following:
```
'guilds' => [
        123456789, // Name: A
        987654321, // Name: B
    ],
```
and at the 
```
'guild_roles' => [
        // Server B
         '987654321' => [
             'XXX', // Role C
         ],
        // Server A
        '123456789' => [
            'XX', // Role A
            'X', // Role B
        ],
    ],
```

In my case i have created a new discord user wich is only member of **Server B**. If i now want to login, i get the error message: _Couldn't get the roles you have._  And further: _HTTP request returned status code 404:\n{\"message\": \"Unknown Guild\", \"code\": 10004}\n_

Okay, but what is now that problem there? After looking into your DiscordController a finaly found the bug: Its the foreach loop. The [loop](https://github.com/JakyeRU/Larascord/blob/2a869aceb972fd25aa56556f7ac8f7d75fa4dbbd/src/Http/Controllers/DiscordController.php#L88) goes over the guild_roles, and my discord user is only part of one server. But the loop does not check this. My User is only on Server B as i say. So when the loop comes to Server A in the guild_roles key, then it throws the Exception because my user is not in the Server A.

So the solution/fix is, that this foreach loop must check however the user is on that server.

**Comment by JakyeRU** [comment]
I'll take a look. Thank you!

**Comment by JakyeRU** [comment]
Hello,

I have added a try/catch block that catches any exceptions from the `getGuildMember` method.

This should fix this issue. Thank you!
